image: gcc

stages:
  - setup
  - build-dbg
  - build

setup:
  stage: setup
  script:
    - apt-get update  -qq
    - apt-get install -qq -y make

build-dbg:
  stage: build-dbg
  script:
    - make all -B DEBUG=yes

  artifacts:
    name: "edil-dbg"
    paths:
      - bin/edil

build:
  stage: build
  script:
    - make all -B DEBUG=no

  artifacts:
    name: "edil"
    paths:
      - bin/edil
