#!/bin/bash

echo Keybindings
echo ===========
echo
echo "The following are edil's default keybindings, generated by the"
echo "command \`edil --binds.\` The script [doc/genkeys.sh](doc/genkeys.sh)"
echo "has generated this file."
echo

bin/edil --binds | sed 's/^ | \([0-9a-f]\{3\}\) \([^ ]*\)     / | `\2 (\1)` /g'
